//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTicket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYDINHGIAVE
    {
        public string MaHang { get; set; }
        public string MaLoai { get; set; }
        public Nullable<double> TiLe { get; set; }
        public Nullable<decimal> TienGiam { get; set; }
        public Nullable<decimal> TienPhi { get; set; }
        public Nullable<decimal> TienLaiVe { get; set; }
        public Nullable<decimal> TienHuyVe { get; set; }
    
        public virtual HANGHANGKHONG HANGHANGKHONG { get; set; }
        public virtual LOAIHANHKHACH LOAIHANHKHACH { get; set; }
    }
}
