//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTicket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VECHUYENBAY
    {
        public string MaVe { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
        public string MaLoai { get; set; }
        public string HoTen { get; set; }
        public string GioTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string MaHoaDon { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual LOAIHANHKHACH LOAIHANHKHACH { get; set; }
    }
}
